"""
Django settings for must_mrejesho project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@w8hyiy627%04$-a0ckh5spk^usb&=lp*6-4p%gkm16)i)46jq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1' , '192.168.3.2','.vercel.app', '.now.sh']
# For deployment, add your real domain, e.g. ALLOWED_HOSTS = ['mrejesho.must.ac.tz']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'departments',
    'feedback',
    'notifications',
    'adminpanel',
    'accountability',
    'channels',
]

ASGI_APPLICATION = 'must_mrejesho.asgi.application'

# In-memory channel layer configuration (requires channels package)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    }
}

AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'feedback:dashboard'
LOGOUT_REDIRECT_URL = 'accounts:login'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'must_mrejesho.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'must_mrejesho.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- Email (objective 3: automated notifications) ---
# Defaults to printing emails to the console for local development.
# For real delivery, set these environment variables and switch EMAIL_BACKEND to:
#   'django.core.mail.backends.smtp.EmailBackend'
import os

EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'MUST e-Mrejesho <no-reply@must.ac.tz>')

# --- Django admin branding (django-jazzmin) ---
JAZZMIN_SETTINGS = {
    "site_title": "MUST e-Mrejesho Admin",
    "site_header": "MUST e-Mrejesho",
    "site_brand": "MUST e-Mrejesho",
    "welcome_sign": "Student Government Accountability & Feedback System",
    "copyright": "Mbeya University of Science and Technology",
    "search_model": ["feedback.Feedback", "accounts.User"],
    "custom_css": "css/admin-must-theme.css",

    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth.Group": "fas fa-users-cog",
        "accounts.User": "fas fa-user-graduate",
        "departments.Department": "fas fa-building",
        "feedback.Feedback": "fas fa-comment-dots",
        "feedback.FeedbackUpdate": "fas fa-history",
        "notifications.Notification": "fas fa-bell",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    "order_with_respect_to": ["accounts", "departments", "feedback", "notifications"],

    "topmenu_links": [
        {"name": "View Site", "url": "/", "new_window": True},
        {"name": "Live Dashboard", "url": "/feedback/", "new_window": True},
    ],

    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",

}

JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-light",
    "navbar_fixed": True,
    "no_navbar_border": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_fixed": True,
    "brand_colour": "navbar-success",
    "accent": "accent-warning",
    "theme": "flatly",
    "button_classes": {
        "primary": "btn-success",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
