# Generated by Django 6.0.6 on 2026-07-01 23:02

import django.db.models.deletion
import feedback.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(default=feedback.models.generate_tracking_number, editable=False, max_length=20, unique=True)),
                ('category', models.CharField(choices=[('COMPLAINT', 'Malalamiko (Complaint)'), ('SUGGESTION', 'Mapendekezo (Suggestion)'), ('INQUIRY', 'Maulizo (Inquiry)'), ('COMPLIMENT', 'Pongezi (Compliment)')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='feedback_attachments/%Y/%m/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IN_PROGRESS', 'In Progress'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('escalation_level', models.PositiveSmallIntegerField(choices=[(1, 'Representative'), (2, 'Admin')], default=1)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, help_text='SLA deadline before auto-escalation is due', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_feedback', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_items', to='departments.department')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_type', models.CharField(choices=[('COMMENT', 'Comment'), ('STATUS_CHANGE', 'Status Change'), ('ESCALATION', 'Escalation'), ('RESOLUTION', 'Resolution'), ('ASSIGNMENT', 'Assignment')], default='COMMENT', max_length=20)),
                ('message', models.TextField()),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='feedback.feedback')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
