# Generated by Django 6.0.6 on 2026-07-03 20:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ACADEMICS', 'Academics'), ('HOSTELS', 'Hostels & Housing'), ('WELFARE', 'Student Welfare'), ('INFRASTRUCTURE', 'Infrastructure & Facilities'), ('FINANCE', 'Finance & Budgeting'), ('GENERAL', 'General Governance')], default='GENERAL', max_length=30)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('STALLED', 'Stalled')], default='NOT_STARTED', max_length=20)),
                ('evidence', models.TextField(blank=True, help_text='Evidence/notes detailing implementation progress or completion')),
                ('evidence_file', models.FileField(blank=True, help_text='Upload official proof, photos, or documents confirming resolution', null=True, upload_to='promise_evidence/')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('MINUTES', 'Meeting Minutes'), ('LEGISLATION', 'Legislation & Constitution'), ('FINANCIAL', 'Financial Report'), ('BUDGET', 'Budget Report'), ('OTHER', 'Other Document')], default='OTHER', max_length=20)),
                ('file', models.FileField(upload_to='public_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepresentativeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True, help_text='Key goals or objectives during tenure (use bullet points or newlines)')),
                ('manifesto', models.TextField(blank=True, help_text='Full manifesto text')),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='rep_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rep_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
